"""The dataset discovery script.

Its whole job is to keep two things apart: "we asked the platform and this
dataset does not exist" and "we could not reach the platform". Conflating them
produces a confident list of datasets to delete, generated by a network outage.

The script cannot be run against the live platform from here, so what is tested
is the reasoning, with the HTTP layer replaced.
"""

import importlib.util
import pathlib
import sys

import pytest
import requests

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

spec = importlib.util.spec_from_file_location(
    "discover_planning", ROOT / "scripts" / "discover_planning_datasets.py")
discover = importlib.util.module_from_spec(spec)
spec.loader.exec_module(discover)


@pytest.fixture(autouse=True)
def _no_network(monkeypatch):
    def boom(*a, **k):
        raise AssertionError("a test tried to make a real HTTP request")
    monkeypatch.setattr(discover.requests, "get", boom)


def fake_http(monkeypatch, table):
    """Answer `_get` from a table keyed by a path fragment. A value of
    `requests.RequestException` is raised rather than returned."""
    def _get(path, params=None):
        for fragment, payload in table.items():
            if fragment in path:
                if isinstance(payload, type) and issubclass(payload, Exception):
                    raise payload("simulated")
                return payload
        return None
    monkeypatch.setattr(discover, "_get", _get)


FEATURE = {"properties": {"flood-risk-type": "Flood Zone 3", "name": "x"}}


# ---------------------------------------------------------------------------
# The distinction the script exists to preserve
# ---------------------------------------------------------------------------
def test_unreachable_is_not_reported_as_nonexistent(monkeypatch):
    fake_http(monkeypatch, {"/dataset/": requests.ConnectionError})
    r = discover.probe("flood-risk-zone", 51.2, -0.5)
    assert r["exists"] is None, "a network failure must not read as 'no such dataset'"
    assert "error" in r


def test_a_missing_dataset_is_reported_as_missing(monkeypatch):
    fake_http(monkeypatch, {})            # every path 404s to None
    r = discover.probe("not-a-dataset", 51.2, -0.5)
    assert r["exists"] is False


def test_an_existing_dataset_reports_its_attributes(monkeypatch):
    fake_http(monkeypatch, {
        "/dataset/": {"dataset": "flood-risk-zone"},
        "/entity.geojson": {"features": [FEATURE]},
    })
    r = discover.probe("flood-risk-zone", 51.2, -0.5)
    assert r["exists"] is True
    assert r["features_here"] == 1
    assert "flood-risk-type" in r["attributes"]


def test_exists_but_empty_here_is_not_a_failure(monkeypatch):
    """There is no coal mining in Surrey. An empty answer for one test area
    says nothing about whether the dataset is usable."""
    fake_http(monkeypatch, {
        "/dataset/": {"dataset": "coal-mining"},
        "/entity.geojson": {"features": []},
    })
    r = discover.probe("coal-mining", 51.2, -0.5)
    assert r["exists"] is True
    assert r["features_here"] == 0
    assert "error" not in r


# ---------------------------------------------------------------------------
# The flood-zone attribute check, which is why this was written
# ---------------------------------------------------------------------------
def test_it_confirms_a_correct_filter_attribute(monkeypatch, capsys):
    fake_http(monkeypatch, {
        "/dataset/": {"dataset": "flood-risk-zone"},
        "/entity.geojson": {"features": [FEATURE]},
    })
    assert discover.show_attributes("flood-risk-zone", 51.2, -0.5) == 0
    assert "OK" in capsys.readouterr().out


def test_it_fails_loudly_on_a_wrong_filter_attribute(monkeypatch, capsys):
    """The scenario the flood factors shipped with: the attribute name came
    from a schema, not from a response."""
    fake_http(monkeypatch, {
        "/dataset/": {"dataset": "flood-risk-zone"},
        "/entity.geojson": {"features": [{"properties": {"flood-zone": "3"}}]},
    })
    assert discover.show_attributes("flood-risk-zone", 51.2, -0.5) == 1
    out = capsys.readouterr().out
    assert "WRONG" in out
    assert "fix open_data.py" in out


def test_the_attribute_mode_also_keeps_offline_apart_from_missing(monkeypatch):
    """The same conflation, on the other code path.

    `main()` had a test for this and `show_attributes` did not, so running the
    flood check offline printed "no such dataset on the platform" about a
    dataset the app reads in production. Exit 2 means "could not ask".
    """
    fake_http(monkeypatch, {"/dataset/": requests.ConnectionError})
    assert discover.show_attributes("flood-risk-zone", 51.2, -0.5) == 2


def test_it_reads_attributes_from_the_nested_form(monkeypatch):
    nested = {"properties": {"json": {"flood-risk-type": "Flood Zone 2"}}}
    assert "flood-risk-type" in discover.attribute_names(nested)


# ---------------------------------------------------------------------------
# Candidates must stay candidates
# ---------------------------------------------------------------------------
def test_no_candidate_is_silently_registered():
    """The script proposes; `open_data.py` disposes. A candidate that quietly
    became real would defeat the point of having a discovery step."""
    import open_data
    registered = {s.dataset for s in open_data.PLANNING_DATASETS.values()}
    for c in discover.CANDIDATES:
        if c.note.startswith("SHIPPED"):
            assert c.dataset in registered
        else:
            assert c.dataset not in registered, (
                f"{c.dataset} is registered as real but is still listed as an "
                f"unverified candidate — one of the two is wrong")


def test_every_candidate_names_a_real_catalogue_factor():
    import catalog
    for c in discover.CANDIDATES:
        assert c.factor in catalog.FACTOR_BY_ID, \
            f"{c.factor} is not in the catalogue"


def test_every_candidate_declares_its_confidence():
    for c in discover.CANDIDATES:
        assert c.confidence in ("documented", "likely", "guess")
