/**
 * Work out which supplied assets actually exist, and write that down.
 *
 * The browser cannot ask the filesystem what is in `public/assets`, and a
 * component that renders an `<img>` and waits for `onError` shows a broken
 * frame first. So the presence of every slot is resolved here, at build time,
 * into a small generated module the site imports.
 *
 * Runs from `predev` and `prebuild`. Drop a file in, restart, it appears.
 *
 * It also prints a checklist, because the useful question while art-directing
 * is "what is still missing", and the answer should be in the terminal rather
 * than found by scrolling the site looking for grey rectangles.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = new URL('..', import.meta.url).pathname
const ASSET_DIR = join(ROOT, 'public', 'assets')
const SLOTS_SRC = join(ROOT, 'src', 'site', 'assets.ts')
const OUT = join(ROOT, 'src', 'site', 'assets.generated.ts')

const SECTIONS = ['hero', 'product', 'evidence', 'field', 'marketing', 'brand']

/*
 * The slot table is TypeScript, and this is a plain Node script, so the
 * filenames are read out of the source rather than imported. Regex parsing is
 * usually a bad idea; here the alternative is a TypeScript loader in the build
 * for one array of strings, and the shape being matched is a literal this file
 * and assets.ts both control.
 */
const src = readFileSync(SLOTS_SRC, 'utf8')
const slots = [...src.matchAll(
  /id:\s*'([^']+)',\s*kind:\s*'(image|video)',\s*section:\s*'([^']+)',\s*\n?\s*file:\s*'([^']+)'(?:,\s*poster:\s*'([^']+)')?/g,
)].map(([, id, kind, section, file, poster]) => ({ id, kind, section, file, poster }))

if (!slots.length) {
  console.error('assets: could not read any slots from src/site/assets.ts — '
    + 'has its shape changed? Refusing to write an empty manifest.')
  process.exit(1)
}

for (const section of SECTIONS) mkdirSync(join(ASSET_DIR, section), { recursive: true })

const present = {}
const missing = []
let supplied = 0

for (const slot of slots) {
  const path = join(ASSET_DIR, slot.section, slot.file)
  const has = existsSync(path)
  const posterPath = slot.poster ? join(ASSET_DIR, slot.section, slot.poster) : null
  const hasPoster = posterPath ? existsSync(posterPath) : false
  present[slot.id] = { file: has, poster: hasPoster }
  if (has) supplied++
  else missing.push(`${slot.section}/${slot.file}`)
  if (slot.poster && has && !hasPoster) {
    console.warn(`assets: ${slot.file} has no poster (${slot.poster}) — `
      + 'the first frame will be blank and reduced-motion visitors get nothing')
  }
}

/*
 * Files sitting in the folders that no slot points at.
 *
 * Worth saying out loud: the usual cause is a typo or a phone's `IMG_4821.JPG`
 * dropped in hopefully, and silently ignoring it means someone believes they
 * supplied a picture that is not on the site.
 */
const known = new Set(slots.flatMap((s) => [
  `${s.section}/${s.file}`, s.poster ? `${s.section}/${s.poster}` : null,
].filter(Boolean)))
const strays = []
for (const section of SECTIONS) {
  const dir = join(ASSET_DIR, section)
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.') || name === 'README.md') continue
    if (!statSync(join(dir, name)).isFile()) continue
    if (!known.has(`${section}/${name}`)) strays.push(`${section}/${name}`)
  }
}

writeFileSync(OUT, `/* Generated by scripts/build-assets.mjs — do not edit.
 *
 * Which asset files exist in public/assets at build time. Drop a file in and
 * re-run (npm run assets, or any dev/build) to update this.
 */
export const SUPPLIED: Record<string, { file: boolean; poster: boolean }> =
${JSON.stringify(present, null, 2)}

/** True when at least one asset has been supplied. Used to decide whether the
 *  site presents itself as art-directed or as awaiting artwork. */
export const ANY_SUPPLIED = ${supplied > 0}
`)

console.log(`assets: ${supplied}/${slots.length} supplied`)
if (missing.length) {
  console.log(`assets: awaiting ${missing.length} file${missing.length === 1 ? '' : 's'}`)
  for (const m of missing) console.log(`  · public/assets/${m}`)
}
if (strays.length) {
  console.warn(`assets: ${strays.length} file(s) in public/assets match no slot `
    + 'and will not appear anywhere:')
  for (const s of strays) console.warn(`  ! public/assets/${s}`)
}
