#!/usr/bin/env python3
"""
Generate DATA_LICENSING.md from the catalogue.

    python3 scripts/build_licensing_doc.py

Hand-written licensing tables rot. A base gets added, the table does not, and
six months later the document says the product uses 43 sources when it uses
45 — at which point it is worse than nothing, because somebody will rely on it.

So this is generated from `catalog.py`, which is where the licence strings
actually live and what the running code actually reads. Re-run it after
touching the catalogue; `tests/test_licensing.py` fails if the file drifts.

**It reports what the repository asserts, not what the law says.** Every
licence string was written from dataset documentation by somebody who is not a
lawyer, and no licence page has been fetched — this environment cannot reach
one. `scripts/verify_licensing.py` is the other half.
"""

import datetime as dt
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import catalog       # noqa: E402
import licensing     # noqa: E402

OUT = ROOT / "DATA_LICENSING.md"

HEADER = """# Data licensing inventory

<!-- GENERATED by scripts/build_licensing_doc.py — do not edit by hand.
     Re-run after changing catalog.py. -->

**Generated {date} from `catalog.py`. Not legal advice, and not verified.**

Every licence string below was recorded in this repository from dataset
documentation, by somebody who is not a lawyer. **No licence page has been
fetched to check any of it** — the environment this was generated in cannot
reach one. The strongest claim available for any row is *"the licence we
recorded appears to permit this"*.

Run `python3 scripts/verify_licensing.py` from a machine with ordinary
internet to check each licence URL still resolves and still says what this
table claims. Until then, treat the whole table as **LEGAL REVIEW REQUIRED**.

## What the states mean

| State | Meaning |
| --- | --- |
| `cleared` | The recorded licence appears to permit commercial use, and nothing about this project's use of it is outstanding. |
| `conditional` | Appears permitted subject to something unresolved — an unconfirmed licence, an attribution condition, a plan tier. |
| `unknown` | Nobody has established the position. |
| `blocked` | Must not reach a customer-facing output. Enforced in `licensing.py`, refused at the API boundary before the source is queried. |

`conditional` still serves. The condition is for a human to resolve, not a
reason to withhold a number the product currently depends on — and conflating
the two would make the `blocked` switch too blunt to ever be turned on.

## Summary

| State | Bases | Factors |
| --- | ---: | ---: |
{summary_rows}

"""


def main() -> int:
    s = licensing.summary()
    summary_rows = "\n".join(
        f"| `{state}` | {s['base_counts'][state]} | {s['factor_counts'][state]} |"
        for state in (licensing.CLEARED, licensing.CONDITIONAL,
                      licensing.UNKNOWN, licensing.BLOCKED))

    out = [HEADER.format(date=dt.date.today().isoformat(),
                         summary_rows=summary_rows)]

    conditional = [b for b in catalog.BASES
                   if licensing.status_for_base(b["id"]) != licensing.CLEARED]
    if conditional:
        out.append("## Not cleared — these are the ones that matter\n")
        for b in conditional:
            state = licensing.status_for_base(b["id"])
            out.append(f"### `{b['id']}` — {state}\n")
            out.append(f"- **Name** {b['name']}")
            out.append(f"- **Publisher** {b['source']}")
            out.append(f"- **Recorded licence** {b['licence']}")
            out.append(f"- **Why** {licensing.reason_for_base(b['id'])}")
            out.append(f"- **Source page** {b['url']}")
            n = sum(1 for f in catalog.FACTORS if f["base"] == b["id"])
            out.append(f"- **Factors affected** {n}\n")

    out.append("## Every base\n")
    out.append("| Base | Publisher | Recorded licence | Commercial (as recorded) "
               "| State | Factors | Attribution required | Source |")
    out.append("| --- | --- | --- | --- | --- | ---: | --- | --- |")
    for b in sorted(catalog.BASES, key=lambda x: x["id"]):
        n = sum(1 for f in catalog.FACTORS if f["base"] == b["id"])
        attrib = (b.get("attribution") or "").replace("|", "/")
        out.append(
            f"| `{b['id']}` | {b['source']} | {b['licence']} "
            f"| {b.get('commercial', '?')} | `{licensing.status_for_base(b['id'])}` "
            f"| {n} | {attrib or '—'} | {b['url']} |")

    out.append("""
## What this table does not cover

- **Software dependencies.** npm and PyPI package licences are not here; see
  `docs/IP_AUDIT.md` for what was and was not checked.
- **Anything fetched at request time that is not in the catalogue** — map
  tiles, glyphs, the geocoder. Those are listed in `docs/IP_AUDIT.md`.
- **Whether the recorded licence is correct.** That is the whole open
  question, and it is what `scripts/verify_licensing.py` exists to reduce.
""")

    OUT.write_text("\n".join(out) + "\n")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    print(f"  {s['base_counts'][licensing.CLEARED]} cleared, "
          f"{s['base_counts'][licensing.CONDITIONAL]} conditional, "
          f"{s['base_counts'][licensing.UNKNOWN]} unknown, "
          f"{s['base_counts'][licensing.BLOCKED]} blocked")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
