"""The mock backend, as a Vercel serverless function.

Cloud Run is blocked on billing, so the deployed frontend has no API to talk
to and shows an error where the data should be. This serves the same
credential-free backend the frontend already uses in development, from the
same origin as the site, so `/` works end to end with no Google account
involved at all.

What this is NOT: it does not touch Earth Engine. Every factor it returns is
generated by `series.py`, which is exactly what the mock has always been for.
`X-Contour-Mock: true` is on every response, the catalogue still reports each
factor's `source` as `generated`, and the UI still labels it. When Cloud Run
is deployed, point vercel.json's `/api/:path*` rewrite back at it and this
becomes unused.

The Python files live at the repository root because the Cloud Run image and
the test suite both expect them there. `includeFiles` in vercel.json puts them
in the bundle; this adds the root to sys.path so the imports resolve.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from mock_ee_backend import app  # noqa: E402

# Vercel's Python runtime looks for a module-level ASGI app called `app`.
__all__ = ["app"]
